---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: dmcobkt
      aws_access_key: AKIAZOGSWYVYCWFLKJ7Q
      aws_secret_key: fpHkLnRbAu0KyJShLvBsmDEEl/NYM0k9qXivo+2G
      state: present
      region: ap-south-1
      versioning: no
      tags:
         name: dmcobkt
         type: example
     # public_access:
         # BlockPublicAcls: true
          #IgnorePublicAcls: true
         # BlockPublicPolicy: true
         # RestrictPublicBuckets: true
    #  register: module_result
      policy: "{{ lookup( 'file','mybucket_policy.json' )}}"
